feat: Improved completion sorting that takes into account the current word and prefix (strict then camel-hump)
redhat-developer/lsp4ij pull request #705
Opened 2024-12-14 16:17 UTC by SCWells72

Opening this initially as a draft PR, but this brings over some of the completion ordering enhancements that I've added to the completion contributors in my own plugin. The idea is that the initial offered completions should be as close to what the user is wanting as possible given the available information at the time that completions are triggered.

First, completion sorting now takes into account configured language case sensitivity.

Next, if completions are triggered in the context of an existing identifier, any matches for that identifier should be listed first with exact matches (again, taking into account case-sensitivity) before starts-with matches before contains matches:

![image](https://github.com/user-attachments/assets/f16dd671-e571-4e63-90f7-13ba7a0b11d3)

Next, the prefix is considered with exact prefix matches listed before camel-hump prefix matches:

**Exact match**
![image](https://github.com/user-attachments/assets/de1e8fbe-3aa6-40af-9e3e-3b00ec7920f5)

**Camel-hump match**
![image](https://github.com/user-attachments/assets/67d15a4c-1193-4b50-89bc-c3f6a13f332c)

Here's another example from CSS since all of the above are from TypeScript:

![image](https://github.com/user-attachments/assets/2b70d85c-779b-4669-b073-57554790941f)

If this looks good -- taking into account feedback, of course -- I'll update `CompletionItemComparatorTest` with comprehensive unit tests for the new comparator logic.

2024-12-14 19:39 UTC, SCWells72 commented
@angelozerr mentioned that sorting should be using `sortText`, so it's worth providing context on why the new contextual aspects of sorting use `label` instead:

You expressly don't want to do that because it defeats the entire point of the changes I made.

The problem you're solving is that you're trying to insert some word of some sort, typically a keyword. If you sort by the sort text -- which is often something like an integer value as shown in the image below (being sorted as text which has its own issues) -- the resulting sort order doesn't take into account insertion context at all, e..g:

![image](https://github.com/user-attachments/assets/8dba1add-29a1-4aea-a3df-e752db5e92f3)

If you look at how IntelliJ IDEA and other JetBrains IDEs sort completions, they take into account the same things I am here, but also things like assignability and declaration proximity which we don't have (easily) from LSP, and of course also machine learning statistics around previously-selected completions in a given context.

With this change it now tries to sort by the keyword/identifier you're trying to insert by looking at the word that already exists at the point of insertion and/or the partial word prefix that's already been typed. And if none of that applies, it degrades gracefully to the original sorting behavior anyway...well, now with proper consideration of language grammar case-sensitivity.

The best way to get a feel for what this change does is to try it. Try completions with and without this change and see the difference in accuracy in terms of what you're actually trying to insert at the caret. I think you'll find that, with these changes, it's quite accurate, and without, you have to type more characters before the `PrefixMatcher` filter kicks in enough to narrow the offered completions down to what you originally wanted.

2024-12-22 17:42 UTC, SCWells72 commented
@angelozerr **after the holidays** (i.e., "don't even look at this anytime soon while you should be spending time with family and friends"), I'd love to start working this one toward a merge. I've (hopefully) removed any concerns about behavioral regressions by making this an opt-in client-side configuration option aside from the case-sensitivty sorting improvements that likely should have been included with the prior code completion case-sensitivity work.

I'll add some additional unit test cases for the comparator changes and that should make this whole.

2024-12-22 17:43 UTC, SCWells72 commented on src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java
> +    public boolean isResolveCompletionSupported(@NotNull PsiFile file) {
All callers were passing non-null values and the `isResolveCompletionSupported()` expects a non-null argument, so I changed the nullability annotation to match reality.

2024-12-22 17:46 UTC, SCWells72 commented on src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
> +        boolean useContextAwareSorting = clientFeatures.getCompletionFeature().useContextAwareSorting(originalFile);
The new features are now opt-in. When disabled (which is the default), the only difference vs. prior behavior should be properly respecting the language case-sensitivity config setting.

2024-12-22 17:47 UTC, SCWells72 commented on src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java
> +        public boolean useContextAwareSorting = false;
The opt-in config option.

2024-12-22 17:47 UTC, SCWells72 commented on src/test/java/com/redhat/devtools/lsp4ij/features/completion/CompletionItemComparatorTest.java
> +    private final CompletionItemComparator comparator = new CompletionItemComparator(null, null, false);
I'll add more test cases here to confirm proper behavior of the new context-aware features of this comparator.

2024-12-22 18:29 UTC, angelozerr commented
@SCWells72 I promise you that I will review your PR after my holiday.

A thing that it would be very nice is to improve the compute of the prefix (when textedit is nul, if I remember the prefix is computed for each completion item which is very badl) and to provide an api to customize it to fix https://github.com/redhat-developer/lsp4ij/issues/447#issuecomment-2286334837

2025-01-06 18:15 UTC, SCWells72 commented
This will be the second PR that I plan to run through review. I'll add unit tests for the enhanced comparator today if possible and switch this from draft to ready-for-review.

2025-01-06 20:12 UTC, SCWells72 commented
@angelozerr I've added extensive unit tests for the comparator so this should now be ready for review.

2025-01-06 20:25 UTC, angelozerr requested changes

2025-01-06 20:25 UTC, angelozerr commented on src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java
> + * Copyright (c) 2024 Red Hat Inc. and others.
2025

2025-01-06 20:26 UTC, angelozerr commented on src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java
> +    public boolean isResolveCompletionSupported(@NotNull PsiFile file) {
Please add this new method api in the docs Lsp api markdown

2025-01-06 21:35 UTC, SCWells72 commented on src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java
> +        return clientConfiguration != null ? clientConfiguration.completion.useContextAwareSorting : super.useContextAwareSorting(file);
As this is an opt-in feature, I didn't update any of the templates to specify the new config setting. The default value is, of course, `false`/disabled. Personally I think that most folks would want it, but I didn't want to assume that by setting it to true in the templates. If you agree that I should, I'll be happy to do so.

2025-01-10 08:16 UTC, angelozerr commented
@SCWells72 I have played with your PR and I love the idea but the sort have some strange behaviour, see the following demo:

![CompletionSortBug](https://github.com/user-attachments/assets/c42b060b-6ca6-4507-b286-6e156b5a22c5)

2025-01-10 16:55 UTC, SCWells72 commented on src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java
> +        return clientConfiguration != null ? clientConfiguration.completion.useContextAwareSorting : super.useContextAwareSorting(file);
I pushed a commit that enables this by default, so I don't think any template updates are needed at this point.

2025-01-10 16:56 UTC, SCWells72 commented
> @SCWells72 I have played with your PR and I love the idea but the sort have some strange behaviour, see the following demo:

This should now be addressed.

2025-01-10 16:57 UTC, SCWells72 commented on src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
> +        boolean useContextAwareSorting = clientFeatures.getCompletionFeature().useContextAwareSorting(originalFile);
Actually the new feature is now enabled by default.

2025-01-10 17:36 UTC, merged